- name: Updating Debian Servers
  hosts:  debian
  remote_user:  root
  tasks:
    - name: Updating all packages to the latest version
      apt:
        upgrade:  full
        autoremove: yes
        update_cache: yes

- name: Updating RHEL Servers
  hosts:  rhel
  remote_user:  root  
  tasks:
    - name: Updating all packages to the latest version
      yum:
        name: "*"
        state:  latest